### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Rhodonvt** [Jalalx/HttpClientCodeGenerator#11]
Hi!

I want to publish an updated version of this library (using an `IIncrementalGenerator`) with other changes in terms of functionality to its own separate repository. However, since there's no license file, I'm not sure if that's allowed.

Can you add a license file, or give me permission to publish my own (heavily modified) version with an explicit (open source) license?
I'll add a link to your repository in the credits, of course.

Thanks!

**Comment by Jalalx** [comment]
Added the MIT license, feel free to use it as you want.
