### ISSUE TITLE
Wrong statement

### ISSUE THREAD

**Issue by mspectr** [Jalalx/HttpClientCodeGenerator#2]
In DependenciesManager line 23

`  if (!resourceName.EndsWith(".cs"))
    {
        // Not a C# file, discarded.
   }
`

this is actually not true. 
In .NET 5 project, visual studio 2019 - I changed a class filetype to .txt cleaned and recompiled - worked
Added some random characters to class declaration - compilation failed.

I doubt it might have any impact but you can't definitely assume that only .cs files are relevant

**Comment by Jalalx** [comment]
Thank you for mentioning it. But this doesn't affect the source generation process since embedded source files are all `.cs` files anyway.
