### ISSUE TITLE
Name of the class should be the full name ( including namespace)

### ISSUE THREAD

**Issue by ignatandrei** [Jalalx/HttpClientCodeGenerator#3]
I have several examples of Roslyn Source Code Generators at https://github.com/ignatandrei/RSCG_Examples/ 
I have tried to add yours too .
 I have put WeatherForecast in a new project - and now gives an error when compiling.
The problem is that the name of the class that is returns should be the full name, not the partial name.

See the error from https://github.com/ignatandrei/RSCG_Examples/ , folder  HttpClientCodeGenerator/src/HttpClientTestWebSite

**Comment by Jalalx** [comment]
Thank you @ignatandrei for mentioning it, I'll fix it in this weekend!

**Comment by Jalalx** [comment]
@ignatandrei Please update the package to version `0.5.3`. It should work as you expected.

**Comment by ignatandrei** [comment]
It works. However, now it does not deserialize . Could you get the solution from  https://github.com/ignatandrei/RSCG_Examples/  ,  folder HttpClientCodeGenerator/src/HttpClientTestWebSite and see why it does not deserialize correctly the 
```chsarp
var w = await userService.GetWeather(1);
Console.WriteLine($"{w.Summary}");
```

? 
It is strange ...

**Comment by ignatandrei** [comment]
What is really really curious is that the answer comes as string.  However, .....

**Comment by ignatandrei** [comment]
I have discovered the problem
```csharp
var options = new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true
};
var weatherForecast = JsonSerializer.Deserialize<WeatherForecast>(jsonString, options);
```

and you have
```csharp
private static T Deserialize<T>(string json) => System.Text.Json.JsonSerializer.Deserialize<T>(json);
```

Could you modify this also ?

**Comment by Jalalx** [comment]
@ignatandrei Just updated to `0.6.0`. Please consider changing the default `JsonSerializerOptions` properties as you wish. For now, by default the `JsonSerializerOptions.PropertyNameCaseInsensitive` is set to `true` to cover most use cases.

You can access the default `JsonSerializerOptions` instance from `HttpClientHelper.DefaultJsonSerializerOptions`.
