### ISSUE TITLE
Generate both WebApi and HttpClient

### ISSUE THREAD

**Issue by ElderJames** [Jalalx/HttpClientCodeGenerator#7]
Hi @Jalalx , I think we can generate both WebApi and HttpClient by source generators, like a RPC.

**Comment by Jalalx** [comment]
Can you elaborate? Or a code sample for what you mean?

**Comment by ElderJames** [comment]
Firstly, add a service class or interface, like what in your readme but should be implemented:

```
    public partial class ToDoService
    {
        [HttpGet("todos/{id}")]
        public partial async Task<ToDoItem> GetToDoItemByIdAsync(int id)
        {
                 return await _db.GetById(id);
        }
    }
```

Then, generator the WebAPI and HttpClient:

WebAPI :
```
public class ToDoController: ApiController
{
    private ToDoService _toDoService;

    pubilc ToDoController(ToDoService toDoService)
    {
         _toDoService=toDoService;
    }
    
     public Task<ToDoItem> GetToDoItemByIdAsync(int id)
     {
          return _toDoService.GetToDoItemByIdAsync(id);
     }
}
```
The HttpClient just like current design.

**Comment by Jalalx** [comment]
Yes, that is possible but developers prefer to implement web api part manually so that they can have full control over the details.

Supporting web api generation is out of current projects scope.

**Comment by ElderJames** [comment]
I just think it makes more sense that the user only needs to care about the business and not manage the configuration of the api.

**Comment by Jalalx** [comment]
Thank you again for providing feedback. Feel free to fork the project and implement the desired feature.
