### ISSUE TITLE
Route parameters not supported when `string` value

### ISSUE THREAD

**Issue by TheJayMann** [Jalalx/HttpClientCodeGenerator#8]
Attempting to generate a method which has a parameter in the route template where the parameter is defined as a `string` causes the parameter to be ignored completely.  This appears to be caused by only considering value typed parameters (not including `CancellationToken`) as valid.  Given that `string` is often used as a primitive even though it is not a value type, I believe it should be special cased in, similar to how `CancellationToken` is currently special cased out.

https://github.com/Jalalx/HttpClientCodeGenerator/blob/37f84c3bfc4a2ee2f2e95bdec666a6130220ca69/src/HttpClientGenerator/Internals/PartialServiceClassSourceBuilder.cs#L312-L315

**Comment by TheJayMann** [comment]
One possible workaround for now is creating a wrapper type.

```csharp
    public readonly struct StringWrapper {
        private readonly string _Value;

        public StringWrapper(string value) => _Value = value;

        public override string ToString() => _Value;

        public static implicit operator StringWrapper(string value) => new(value);

    }
```

**Comment by Jalalx** [comment]
Thank you for reporting it. Please use the NuGet version `0.6.1`.
